/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myappliserverdhcp;

import java.awt.Color;
import java.io.IOException;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.io.*;
import java.util.ArrayList;



/**
 *
 * @author Madickeb Diop
 */
public class Serveur extends javax.swing.JFrame {
    
    ServerSocket server=null;
    Socket client=null;
    DataOutputStream dos=null;
    DataInputStream dis=null;
    

   

    /**
     * Creates new form Serveur
     */
    public Serveur() {
                initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel2 = new javax.swing.JLabel();
        btn_strtServer = new javax.swing.JButton();
        txt_msg = new javax.swing.JTextField();
        btn_send = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_recMsg = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(15, 20, 15, 20));
        getContentPane().setLayout(null);

        btn_strtServer.setText("demarrer serveur");
        btn_strtServer.setBackground(Color.green);
        btn_strtServer.setOpaque(true);
        btn_strtServer.setBorderPainted(false);
        btn_strtServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_strtServerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_strtServer);
        btn_strtServer.setBounds(455, 113, 130, 23);
        getContentPane().add(txt_msg);
        txt_msg.setBounds(10, 375, 289, 30);
        //txt_msg.setText("192.168.1.12");

        btn_send.setText("envoyer");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btn_send, org.jdesktop.beansbinding.ELProperty.create("${background}"), btn_send, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        btn_send.setBackground(Color.green);
        btn_send.setOpaque(true);
        btn_send.setBorderPainted(false);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        getContentPane().add(btn_send);
        btn_send.setBounds(488, 374, 80, 23);

        txt_recMsg.setColumns(20);
        txt_recMsg.setRows(5);
        jScrollPane1.setViewportView(txt_recMsg);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 154, 414, 150);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(191, 50, 97, 0);

        jLabel4.setFont(new java.awt.Font("Arial", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Serveur_DHCP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(179, 1, 267, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myappliserverdhcp/server.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 620, 440);

        bindingGroup.bind();

        setBounds(0, 0, 623, 479);
    }// </editor-fold>//GEN-END:initComponents

    
    

    
    private void btn_strtServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_strtServerActionPerformed
        try {
            // TODO add your handling code here:
            server= new ServerSocket(2000);
            JOptionPane.showMessageDialog(null,"Le serveur est demarré");
            client= server.accept();
            JOptionPane.showMessageDialog(null,"La demande de connnexion du client \n est acceptée par le serveur");
            dos= new DataOutputStream(client.getOutputStream());
            dis= new DataInputStream(client.getInputStream());
            
            
            
            ReceiveMessage serverThread2= new ReceiveMessage(dis,txt_recMsg);
            serverThread2.setDaemon(true);
            serverThread2.setName(" DHCPREQUEST: offre accepté ");
            serverThread2.start(); 
            
            ReceiveMessage serverThread1= new ReceiveMessage(dis,txt_recMsg);
            serverThread1.setDaemon(true);
            serverThread1.setName("DHCPDISCOVER:     Destination     255.255.255.255\n"
                    + "                                      @ip-Source      0.0.0.0 \n"
                    + "                                      @MAC-Client     ff:ff:ff:ff:ff:ff \n\n\n");
                    
                        
                        serverThread1.start();


             
            

                        
                       
                                    //serverThread1.sleep((int) (Math.random()*100000000));


            
            
             
            
            
            //ArrayList<Adresse> a=new Test2().liste();
            
            
            
            
           
            
            
            
            
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(Serveur.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Aucun client  n'est disponible");
            
        }
        
        
    }//GEN-LAST:event_btn_strtServerActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        
        String msg= txt_msg.getText();
                 
        try {
            dos.writeUTF(msg);
        } catch (IOException ex) {
            Logger.getLogger(Serveur.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Serveur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Serveur().setVisible(true);
                
              
                
             
            }
        });
           
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_strtServer;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_msg;
    private javax.swing.JTextArea txt_recMsg;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}

